# Generated by Django 3.2 on 2023-05-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name_plural': 'Рецепт'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name_plural': 'Карта покупок'},
        ),
    ]
