version: '3.3'
services:

  frontend:
    image: maxswallow/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    image: maxswallow/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    env_file:
      - .env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
  db: