# Generated by Django 3.2 on 2023-05-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags_ingr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',), 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name_plural': 'Тэги'},
        ),
    ]
